# Generated by Django 4.1.1 on 2022-09-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('is_published', 'name', 'parent'), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='публикация'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='app_categories',
        ),
    ]
